# Generated by Django 4.1 on 2025-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='destaque',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=2),
        ),
    ]
