# Generated by Django 4.1 on 2025-11-24 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='destaque',
            field=models.IntegerField(default=99, help_text='Priority Rank (0 = High Priority, 5 = Low Priority). Articles outside this range will not be considered highlights.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
